### ISSUE TITLE
about why dista should larger than distb.

### ISSUE THREAD

**Issue by YunpengZhai** [andreasveit/triplet-network-pytorch#3]
Excuse me.
I have a question that why dista should be larger than distb in --train.py --train() function
I mean that distance between ref and pos should be  smaller than ref and neg.
thanks very much!

**Comment by andreasveit** [comment]
Because dista is the distance between ref and neg.
Triplets are in the form (ref, neg, pos).

**Comment by ssdutHB** [comment]
Yep! That's the point.
