### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by kissste** [andreasveit/triplet-network-pytorch#4]
> Processing Triplet Generation ...
> Traceback (most recent call last):
>   File "train.py", line 257, in <module>
>     main()    
>   File "train.py", line 61, in main
>     transforms.Normalize((0.1307,), (0.3081,))
>   File "/home/qwe/triplet-network-pytorch/triplet_mnist_loader.py", line 44, in __init__
>     self.make_triplet_list(n_train_triplets)
>   File "/home/qwe/triplet-network-pytorch/triplet_mnist_loader.py", line 164, in make_triplet_list
>     writer.writerows(triplets)
> TypeError: a bytes-like object is required, not 'str'

**Comment by cdluminate** [comment]
Same error here. The code needs to be ported to python3.

**Comment by Paul0M** [comment]
change 'wb' to 'w' in line 162 in triplet_mnist_loader.py

**Comment by andreasveit** [comment]
Thanks for the comment. The code is updated.
